form/urls.py
from django.urls import path

from . import views
app_name = 'form'

urlpatterns =[
    path('add/', views.add, name='add'),
    path('index/', views.index, name='index'),
] 

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kudos/<int:index>/', views.kudos_or_undo, name='kudos')
]

tk1/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('postcontents/', include('postcontents.urls')),
    path('form/', include('form.urls', namespace='form')),
    path('', include('main.urls')),
    path('',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from form.models import PostModel

# Create your models here.
class Like(models.Model):
    user_kudos = models.ForeignKey(User, on_delete=models.CASCADE)
    post_kudos = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

main/views.py
from django.shortcuts import render, redirect
from .models import Like
from form.models import PostModel
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def home(request):
    count_post = PostModel.objects.all().count()
    postingan = {}
    for pos in PostModel.objects.all():
        if request.user.is_authenticated :
            pos_satuan = {
                "post" : pos,
                "liked" : pos.like_set.filter(user_kudos=request.user) and True or False,
                "kudos" : pos.like_set.all().count()
            }
        postingan[pos.id] = pos_satuan
    postingan1 = {
        'count_post' : count_post,
        'postingan' : postingan
    }
    print(postingan1)
    return render(request, 'main/home.html', postingan1)

@login_required
def kudos_or_undo(request, post_id):
    new_kudos, like_it = Like.objects.get_or_create(user_kudos=User, post_kudos=PostModel.objects.get(id=post_id))
    if not like_it:
        new_kudos.delete()
    return redirect('../')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
{% endblock page_title %}
{% endblock meta %}

{% block content %}
  <div class="container" style="text-align: center;">
    <div class="home-container">
      <a href="{% url 'form:add' %}">Post what you think...</a> <!--link to create post-->
    </div>
    {% if postingan1.count_post == 0 %}
      <div class="home-container">
        <h4>Nothing here. Add the new post.</h4>
      </div>
    {% endif %}
    {% for id,vals in postingan1.postingan.items %}
      {% for val,post in vals.items %}
      <div class="home-container">
        <h4>{{ post.title }}</h4>
        <h5 style="color: #b4b4b4;">{{ post.author.username }}. {{ post.time }}</h5>
        <br>
        <h5>{{ post.content }}</h5>
      </div>
      {% endfor %}
        <div style="text-align: right; display: flex;">
          <a href="">Detail post</a>
          {% if val.liked == True %}
            <a href="{% url 'main:kudos' id %}">Liked!</a>
          {% else %}
            <a href="{% url 'main:kudos' id %}">Like it!</a>
          {% endif %}
          <h5>{{ val.kudos }}</h5>
        </div>
    {% endfor %}
  </div>
{% endblock content %}