postcontents/urls.py
from django.urls import path

from . import views
app_name = 'postcontents'

urlpatterns =[
    path('contents/<int:id>/', views.contents, name='contents'),
    path('otherprofile/<str:parameter>/', views.otherprofile, name='otherprofile')
] 

tk1/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('postcontents/', include('postcontents.urls')),
    path('form/', include('form.urls', namespace='form')),
    path('', include('main.urls')),
    path('',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postcontents/models.py
from django.db import models
from django.conf import settings
from form.models import PostModel
from users.models import Profile
# Create your models here.
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE , default=1)
    komen = models.CharField(max_length=200, blank=False, null=True)
    postingan = models.ForeignKey(PostModel, null=True, on_delete= models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    def _str_(self,):
        return self.komen

postcontents/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['komen']
        widgets = {
            'komen': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'Comment'
                                            })
        }
        labels = {
        "komen": ""
        }

postcontents/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from form.models import PostModel
from users.models import Profile
from .forms import CommentForm
from .models import Comment

# Create your views here.

def contents(request, id):
    postobj = PostModel.objects.get(id=id)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        if not request.user.is_authenticated:
            messages.warning(request, "login required!")
        else:
            instance = form.save(commit=False)
            instance.postingan = postobj
            instance.user = request.user
            instance.save()
        form = CommentForm()

    comments = Comment.objects.all()
    profiles = Profile.objects.all()
    
    context = {
        'postcontent': postobj,
        'comments': comments,
        'commentform': form,
    }
    return render(request, 'content.html', context)

def otherprofile(request, parameter):
    author = User.objects.get(username=parameter)   
    context = {
        'posts' : PostModel.objects.filter(author=author),
        'author': author
    }
    return render(request, 'user/profile.html', context)

postcontents/templates/content.html
{% extends "base.html" %} {% block meta %} {% endblock meta %}{% load static %} {% block content %}
<div class="container" style="width: 100%; height: 100%;padding-bottom: 30%;margin-top: 0;">
    <div class="row justify-content-center">
        <div class="container detail-container">
            <div class="row">
                <div class="col-1">
                    <a href="{% url 'postcontents:otherprofile' parameter=postcontent.author.username %}">
                        <img class="rounded-circle account-img-post" src="{{ postcontent.author.profile.image.url }}">
                    </a>
                </div>
                <div class="col-11" style="padding-top: 0.5%;">
                    <h3 id="contentitle">{{ postcontent.title }}</h1>
                        <a href="{% url 'postcontents:otherprofile' parameter=postcontent.author.username %}" style="color: black;">
                            <h6 id="contentuser">{{ postcontent.author }} posted</h6>
                        </a>
                        <h8 id="contentdate">{{ postcontent.time }}</h8>
                </div>
            </div>
            <div class="row">
                <div class="col-1">

                </div>
                <div class="col-11">
                    <p id="thecontent">{{ postcontent.content }}</p>
                </div>
            </div>
            <div class="card-footer" style="text-align: left; background-color: rgba(0, 0, 0, 0);padding-bottom: 0.01%;width: 100%;">
                <div class="form-group-horizontal">
                    <form method='POST'>
                        <div class="row justify-content-left" style="width: 100%;">
                            <div class="col-11">
                                {% csrf_token %} {{ commentform.as_p }}
                            </div>
                            <div class="col-1">
                                <input class="form-control" id="comment-button" type='submit' value='Post' style="top: 0;left: -5%;" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% for comment in comments %} {% if comment.postingan.id == postcontent.id %}
    <div class="row justify-content-center">
        <div class="container comment-container" style="margin-top: 0.1%;">
            <div class="row">
                <div class="col-1">
                    <a href="{% url 'postcontents:otherprofile' parameter=comment.user.username %}">
                        <img class="rounded-circle account-img-comment" src="{{ comment.user.profile.image.url }}">
                    </a>
                </div>
                <div class="col-11" style="padding-top: 0.7%;">
                    <a href="{% url 'postcontents:otherprofile' parameter=comment.user.username %}" style="color: black;">
                        <h6 id="comment-user-name">{{ comment.user }}</h6>
                    </a>
                    <h6 id="commentdate"> {{ comment.time }}</h6>
                    <p id="comment">{{ comment.komen }}</p>
                </div>
            </div>
        </div>
    </div>
    {% endif %} {% endfor %}
</div>
{% endblock content %}